name: Simplecov
on: [push]
jobs:
  Simplecov:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v2
    # Use the action we created in action.yml file to install dependencies.
    - uses: ./.github/actions/setup-rails-app
    - name: Run Simplecov
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        REDIS_URL: redis://localhost:6379/0
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: |
        bundle exec rake db:setup
        bundle exec rspec --format SimpleCov

    - name: Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage